name: tomato_leaf
description: "Final Project Semester 5"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.1
  firebase_database: ^11.1.0
  firebase_messaging: ^15.1.3
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  flutter_screenutil: ^5.9.3
  get: ^4.6.5
  logger: ^2.4.0
  lottie: ^3.1.2
  google_fonts: ^5.1.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  fluttertoast: ^8.2.4
  intl: ^0.18.0
  http_parser: ^4.0.0
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.2.0
  photo_view: ^0.15.0
  flutter_background_service: ^5.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/icons/
