name: tomato_leaf
description: "Final Project Semester 5"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.5
  flutter_svg: ^2.0.10+1
#  firebase_storage: ^12.3.2
#  firebase_database: ^11.1.2
#  firebase_messaging: ^15.1.1
  dio: ^5.5.0+1
  flutter_screenutil: ^5.9.3
  get: ^4.6.5
  logger: ^2.4.0
  lottie: ^3.1.2
  google_fonts: ^5.1.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/icons/
